// Disposable browser context; website only. No Claude, native bridge or personal profile.
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE || path.join(repo, 'extensions/browser/node_modules/playwright/index.mjs')).href);
const assets = new Map([['/', 'index.html'], ...['index.html','styles.css','site.mjs','clawd-game.mjs','clawd-game.css','assets/favicon.svg'].map(file => [`/${file}`, file])]);
const types = { '.html':'text/html; charset=utf-8', '.css':'text/css', '.mjs':'text/javascript', '.svg':'image/svg+xml' };
const server = createServer(async (request, response) => {
  const file = assets.get(new URL(request.url, 'http://localhost').pathname);
  if (!file) { response.writeHead(404).end(); return; }
  try { const data = await readFile(path.join(repo, 'apps/site', file)); response.writeHead(200, {'Content-Type':types[path.extname(file)]}).end(data); }
  catch { response.writeHead(500).end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
let browser;
const checks = [], errors = [], external = [];
const check = name => checks.push(name);
try {
  browser = await chromium.launch({headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:900},colorScheme:'light'});
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (!request.url().startsWith(base)) external.push(request.url()); });
  page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
  await page.goto(base, {waitUntil:'networkidle'});
  assert.match(await page.title(), /Lintel/);
  assert.equal(await page.locator('h1').count(), 1);
  assert.equal(await page.locator('.clawd-game').getAttribute('data-state'), 'ready');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > innerWidth), false);
  check('desktop loads, no overflow, game rests until started');
  await page.getByRole('tab', {name:/保住工作/}).click();
  assert.match(await page.locator('#demo-content').innerText(), /加入加密归档/);
  await page.getByRole('button', {name:'查看示例回执'}).click();
  assert.match(await page.locator('#demo-content').innerText(), /可阅读，不承诺续聊/);
  await page.getByRole('button', {name:'返回示例计划'}).click();
  await page.getByRole('tab', {name:/保住工作/}).focus();
  await page.keyboard.press('ArrowDown');
  assert.equal(await page.getByRole('tab',{name:/看清改动/}).getAttribute('aria-selected'), 'true');
  assert.match(await page.locator('#demo-content').innerText(), /核对后续编辑/);
  check('all demo tabs, receipt/plan and keyboard navigation');
  await page.getByRole('button',{name:'切换到夜色'}).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  check('night theme and local preference survive reload');
  const board = page.getByRole('group',{name:'Clawd 跳跃跑道'});
  await board.scrollIntoViewIfNeeded(); await board.focus(); await page.keyboard.press('Space');
  assert.equal(await page.locator('.clawd-game').getAttribute('data-state'), 'running');
  await page.waitForFunction(()=>Number(document.querySelector('.cg-score').textContent)>0);
  await page.keyboard.press('p');
  assert.equal(await page.locator('.clawd-game').getAttribute('data-state'), 'paused');
  const pausedScore = await page.locator('.cg-score').textContent();
  await page.waitForTimeout(150);
  assert.equal(await page.locator('.cg-score').textContent(), pausedScore);
  await page.getByRole('button',{name:'继续走',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.clawd-game').dataset.state === 'over', null, {timeout:12000});
  assert.ok(Number(await page.locator('.cg-best').textContent())>0);
  await page.getByRole('button',{name:'再来一次'}).click();
  assert.equal(await page.locator('.clawd-game').getAttribute('data-state'), 'running');
  await page.getByRole('link',{name:'源码',exact:true}).focus();
  assert.equal(await page.locator('.clawd-game').getAttribute('data-state'), 'paused');
  await page.getByRole('button',{name:'继续走',exact:true}).click();
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await page.waitForFunction(()=>document.querySelector('.clawd-game').dataset.state === 'paused');
  check('game starts, scores, pauses, resumes, collides, retries, pauses on focus exit and scrolling away');
  await page.reload(); assert.ok(Number(await page.locator('.cg-best').textContent())>0);
  check('best score survives reload');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.cursor').first().evaluate(node=>getComputedStyle(node).animationName), 'none');
  check('reduced motion disables automatic cursor animation');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > innerWidth), false);
  // The viewport protocol reply can precede the real media-query notification.
  await page.waitForFunction(()=>document.querySelector('[role=tablist]').getAttribute('aria-orientation') === 'horizontal', null, {timeout:2000});
  assert.equal(await page.getByRole('tablist').getAttribute('aria-orientation'), 'horizontal');
  await page.locator('.cg-jump').click();
  assert.equal(await page.locator('.clawd-game').getAttribute('data-state'), 'running');
  await page.locator('.cg-pause').click();
  assert.equal(await page.locator('.clawd-game').getAttribute('data-state'), 'paused');
  check('390px mobile layout and direct jump/pause controls');
  await context.close();
  const blocked = await browser.newContext({viewport:{width:390,height:844},hasTouch:true});
  await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Storage denied','SecurityError');}});});
  const blockedPage = await blocked.newPage();
  blockedPage.on('pageerror',error=>errors.push(error.message));
  await blockedPage.goto(base);
  assert.match(await blockedPage.locator('.cg-storage').innerText(), /存储不可用/);
  await blockedPage.locator('.cg-jump').tap();
  assert.equal(await blockedPage.locator('.clawd-game').getAttribute('data-state'), 'running');
  await blockedPage.locator('.cg-pause').tap();
  assert.equal(await blockedPage.locator('.clawd-game').getAttribute('data-state'), 'paused');
  check('touch jump/pause and blocked local storage with temporary scores');
  await blocked.close();
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
  check('no runtime/asset errors or external requests');
  console.log(JSON.stringify({status:'passed',checks},null,2));
} finally {
  await browser?.close(); await new Promise(resolve=>server.close(resolve));
}
