// Synthetic profiles only. Set PLAYWRIGHT_MODULE to an installed playwright index.mjs,
// or install the development dependency. Never uses a personal browser profile.
import assert from 'node:assert/strict';import http from 'node:http';import {mkdtemp,rm,mkdir,writeFile,realpath,cp} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import {execFileSync} from 'node:child_process';
import {persistSyntheticExtension} from './persistent-install.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
execFileSync(process.execPath,[path.join(root,'scripts/build.mjs'),'--fixture']);
await mkdir(path.join(root,'artifacts'),{recursive:true});
const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE;
if(executablePath && !(await realpath(executablePath)).includes('/ms-playwright/chromium-')) throw new Error('Only a Playwright-managed Chromium executable is accepted');
const profile=await mkdtemp(path.join(os.tmpdir(),'lintel-synthetic-browser-'));
const ext=path.join(profile,'synthetic-extension');
await cp(path.join(root,'dist/chromium-fixture'),ext,{recursive:true});
const host=path.join(root,'native-host/target/debug/lintel-browser-host');
execFileSync('cargo',['build','--manifest-path',path.join(root,'native-host/Cargo.toml')],{stdio:'inherit'});
// Must equal the installer's derived state path for `--home profile` so the
// explicit `register --apply` authorization and the host control calls agree.
const state=path.join(profile,os.platform()==='darwin'?'Library/Application Support/Lintel/browser-bridge':'.local/state/lintel/browser-bridge');
const nativeControl=request=>{const result=JSON.parse(execFileSync(host,['control'],{env:{...process.env,LINTEL_BROWSER_STATE:state},input:JSON.stringify(request),encoding:'utf8'}));assert.equal(result.ok,true,JSON.stringify(result.error));return result.data;};
const server=http.createServer((req,res)=>{res.setHeader('Cache-Control','no-store');if(req.url==='/sw.js'){res.setHeader('Content-Type','text/javascript');res.end("self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('message',e=>{if(e.data==='synthetic-writer')e.waitUntil((async()=>{for(let i=0;i<100;i++){const cache=await caches.open('lintel-worker-writer');await cache.put('/writer',new Response('SYNTHETIC'));if(i===0)e.ports[0].postMessage('writing');await new Promise(r=>setTimeout(r,50));}})());});");}else{res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Synthetic storage fixture</title><h1>Synthetic storage fixture</h1>'+ (req.url==='/embed'?'<iframe src="http://localhost:18765/writer"></iframe>':req.url==='/writer'?'<script>setInterval(()=>localStorage.setItem("active-writer","SYNTHETIC"),10)</script>':''));}});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(18765,'127.0.0.1',resolve);});
let context;
// Bootstrap only once. All later launches rely on the native persistent install;
// command-line extension loads do not provide runtime.onStartup evidence.
const launch=(bootstrap=false)=>chromium.launchPersistentContext(profile,{headless:true,ignoreDefaultArgs:['--disable-extensions'],...(executablePath?{executablePath}:{channel:'chromium'}),env:{...process.env,HOME:profile,LINTEL_BROWSER_STATE:state},args:bootstrap?[`--load-extension=${ext}`]:[]});
const extensionWorker=(context,extensionId)=>context.serviceWorkers().find(w=>w.url()===`chrome-extension://${extensionId}/background.js`)||context.waitForEvent('serviceworker',{timeout:15000,predicate:w=>w.url()===`chrome-extension://${extensionId}/background.js`});
async function browserSnapshot(context){
 const cdp=await context.browser().newBrowserCDPSession();let version;
 try{const {processInfo}=await cdp.send('SystemInfo.getProcessInfo');const browser=processInfo.find(p=>p.type==='browser');assert(browser);version=await context.newPage();await version.goto('chrome://version');const commandLine=await version.locator('#command_line').textContent();return {processId:browser.id,extensionLoadFlags:commandLine.match(/--(?:load-extension|disable-extensions-except)(?:=[^\s]+)?/g)||[]};}
 finally{await version?.close();await cdp.detach();}
}
async function bounded(promise,label='browser operation'){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`Synthetic ${label} exceeded 30 seconds`)),30000);})]);}finally{clearTimeout(timer);}}
async function seed(page){
 await page.bringToFront();console.log('seed local storage',page.url());
 await bounded(page.evaluate(()=>{localStorage.setItem('lintel-fixture','SYNTHETIC');document.cookie='lintel_fixture=SYNTHETIC; Path=/; SameSite=Lax; Max-Age=3600';}),'localStorage');
 console.log('seed indexedDB');
 await bounded(page.evaluate(()=>new Promise((resolve,reject)=>{const q=indexedDB.open('lintel-fixture',1);q.onupgradeneeded=()=>q.result.createObjectStore('data');q.onsuccess=()=>{const db=q.result,tx=db.transaction('data','readwrite');tx.objectStore('data').put('SYNTHETIC','key');tx.oncomplete=()=>{db.close();resolve();};};q.onerror=()=>reject(q.error);})), 'IndexedDB');
 console.log('seed CacheStorage');await bounded(page.evaluate(async()=>{const c=await caches.open('lintel-fixture');await c.put('/cached',new Response('SYNTHETIC'));}),'CacheStorage');
 console.log('seed ServiceWorker');await bounded(page.evaluate(async()=>{await navigator.serviceWorker.register('/sw.js');const registration=await navigator.serviceWorker.ready;await new Promise(resolve=>{const channel=new MessageChannel();channel.port1.onmessage=()=>resolve();registration.active.postMessage('synthetic-writer',[channel.port2]);});}),'ServiceWorker');
}
async function observe(page){await page.bringToFront();console.log('observe',page.url());return bounded(page.evaluate(async()=>({localStorage:localStorage.getItem('lintel-fixture'),cookie:document.cookie.includes('lintel_fixture='),indexedDB:(await indexedDB.databases()).map(v=>v.name),cacheStorage:await caches.keys(),serviceWorkers:(await navigator.serviceWorker.getRegistrations()).length})));}
try{
 console.log('launch synthetic Chromium');context=await launch(true);context.setDefaultTimeout(15000);let worker=context.serviceWorkers().find(w=>w.url().startsWith('chrome-extension:'))||await context.waitForEvent('serviceworker',{timeout:15000,predicate:w=>w.url().startsWith('chrome-extension:')});const extensionId=new URL(worker.url()).host;
 const persistent=await persistSyntheticExtension(context,ext,extensionId);worker=persistent.worker;
 console.log('synthetic extension installed through native Chromium recovery');
 const target=await context.newPage(),neighbor=await context.newPage();await target.goto('http://localhost:18765');await neighbor.goto('http://127.0.0.1:18765');await seed(target);await seed(neighbor);assert.equal((await observe(target)).serviceWorkers,1);const embedded=await context.newPage();await embedded.goto('http://127.0.0.1:18765/embed');await embedded.frame({url:'http://localhost:18765/writer'}).waitForFunction(()=>localStorage.getItem('active-writer')==='SYNTHETIC');const beforeNeighbor=await observe(neighbor);console.log('fixtures seeded');
 let popup=await context.newPage();await popup.goto(`chrome-extension://${extensionId}/popup.html`);
 const initialIdentity=await popup.evaluate(async()=>(await chrome.storage.local.get('identity')).identity.instanceId);
 await popup.getByRole('button',{name:'预览站点数据清理',exact:true}).click();await popup.waitForFunction(()=>!document.getElementById('preview-panel').hidden || document.getElementById('error').textContent);assert.equal(await popup.locator('#error').textContent(),'');await popup.getByLabel('我确认以上范围与功能影响').check();await popup.getByRole('button',{name:'授予必要权限并执行一次'}).click();
 await popup.locator('#receipts').getByText('clear · awaiting-browser-restart',{exact:true}).waitFor({timeout:30000});assert(target.isClosed());assert(embedded.isClosed());assert.deepEqual(await observe(neighbor),beforeNeighbor);
 const preparation=await worker.evaluate(async()=>Object.values(await chrome.storage.local.get(null)).find(v=>v?.action?.kind==='clear'));assert.equal(preparation.phase,'awaiting-browser-restart');assert.equal(preparation.result.embeddedWriterTabCount,1);assert.equal(preparation.result.storageDeletion,'not-started');
 const preparedGeneration=await popup.evaluate(async()=>(await chrome.storage.local.get('browserStartupGeneration')).browserStartupGeneration||'initial');assert.equal(preparation.preparedGeneration,preparedGeneration);
 const premature=await popup.evaluate(id=>chrome.runtime.sendMessage({type:'preview',action:{kind:'finishClear',receiptId:id}}),preparation.id);assert.equal(premature.error.code,'browser_restart_required');
 const blocked=await context.newPage();await assert.rejects(blocked.goto('http://localhost:18765'),/ERR_BLOCKED_BY_CLIENT/);await blocked.close();
 const priorBrowser=await browserSnapshot(context);await context.close();const closedAt=new Date().toISOString();assert.throws(()=>process.kill(priorBrowser.processId,0),{code:'ESRCH'});console.log('restart to stop outstanding service worker events');context=await launch();const restartedAt=new Date().toISOString();context.setDefaultTimeout(15000);const restartedBrowser=await browserSnapshot(context);assert.notEqual(restartedBrowser.processId,priorBrowser.processId);assert.deepEqual(restartedBrowser.extensionLoadFlags,[]);worker=await extensionWorker(context,extensionId);popup=await context.newPage();await popup.goto(`chrome-extension://${extensionId}/popup.html`);
 await popup.waitForFunction(async prior=>{const current=(await chrome.storage.local.get('browserStartupGeneration')).browserStartupGeneration;return current&&current!==prior;},preparedGeneration);const observedGeneration=await popup.evaluate(async()=>(await chrome.storage.local.get('browserStartupGeneration')).browserStartupGeneration);assert.equal(await popup.evaluate(async()=>(await chrome.storage.local.get('identity')).identity.instanceId),initialIdentity);
 const startupEvidence={source:'production runtime.onStartup listener; harness never writes or dispatches startup generation',preparedGeneration,observedGeneration,closedAt,restartedAt,priorBrowserProcessId:priorBrowser.processId,priorBrowserProcessExited:true,restartedBrowserProcessId:restartedBrowser.processId,observedRelaunchExtensionFlags:restartedBrowser.extensionLoadFlags,extensionId,identityRetained:true};
 await popup.getByRole('button',{name:'预览重启后继续删除',exact:true}).click();await popup.waitForFunction(()=>!document.getElementById('preview-panel').hidden || document.getElementById('error').textContent);assert.equal(await popup.locator('#error').textContent(),'');await popup.getByLabel('我确认以上范围与功能影响').check();await popup.getByRole('button',{name:'授予必要权限并执行一次'}).click();await popup.locator('#receipts').getByText('finishClear · completed',{exact:true}).waitFor();
 const record=await worker.evaluate(async()=>Object.values(await chrome.storage.local.get(null)).find(v=>v?.action?.kind==='finishClear'));assert.equal(record.result.cookieObservation.remaining,0);assert.equal(record.result.writerHandling,'browser-restarted-after-service-workers-unregistered');
 const preservedNeighbor=await context.newPage();await preservedNeighbor.goto('http://127.0.0.1:18765');assert.deepEqual(await observe(preservedNeighbor),beforeNeighbor);await popup.bringToFront();
 await popup.getByRole('button',{name:'已核对结果，解除站点隔离'}).click();
 const clean=await context.newPage();await clean.goto('http://localhost:18765');const after=await observe(clean);assert.deepEqual(after,{localStorage:null,cookie:false,indexedDB:[],cacheStorage:[],serviceWorkers:0});console.log('target cleared; neighbor preserved; navigation isolation verified');
 assert.equal(await clean.evaluate(()=>localStorage.getItem('active-writer')),null);
 await popup.bringToFront();await popup.getByRole('button',{name:'预览站点权限',exact:true}).click();await popup.getByLabel('我确认以上范围与功能影响').check();await popup.getByRole('button',{name:'授予必要权限并执行一次'}).click();await popup.locator('#receipts').getByText('sitePermission · completed',{exact:true}).waitFor();
 assert.equal(await worker.evaluate(async()=>(await chrome.contentSettings.location.get({primaryUrl:'http://localhost:18765'})).setting),'block');assert.equal(await worker.evaluate(async()=>(await chrome.contentSettings.location.get({primaryUrl:'http://127.0.0.1:18765'})).setting),'ask');
 await popup.getByRole('button',{name:'预览恢复此项设置',exact:true}).click();await popup.getByLabel('我确认以上范围与功能影响').check();await popup.getByRole('button',{name:'授予必要权限并执行一次'}).click();await popup.locator('#receipts').getByText('restore · completed',{exact:true}).waitFor();assert.equal(await worker.evaluate(async()=>(await chrome.contentSettings.location.get({primaryUrl:'http://localhost:18765'})).setting),'ask');console.log('scoped location permission applied and restored');
 await seed(clean); // new login/storage after clear; duplicate commit must not remove it
 await context.close();console.log('restart synthetic browser');context=await launch();worker=await extensionWorker(context,extensionId);
 const page=await context.newPage();await page.goto(`chrome-extension://${extensionId}/popup.html`);const duplicate=await page.evaluate(id=>chrome.runtime.sendMessage({type:'commit',id}),record.id);assert.equal(duplicate.data.phase,'completed');
 const newLogin=await context.newPage();await newLogin.goto('http://localhost:18765');assert.equal((await observe(newLogin)).cookie,true);

 await page.bringToFront();
 const manifestDir=path.join(profile,'NativeMessagingHosts');await mkdir(manifestDir,{recursive:true});await writeFile(path.join(manifestDir,'app.lintel.browser.json'),execFileSync(host,['manifest','chromium',extensionId,host]));
 const install=JSON.parse(execFileSync(host,['register','chrome',extensionId,host,'--home',profile,'--apply'],{env:{...process.env,LINTEL_BROWSER_STATE:state},encoding:'utf8'}));assert.equal(install.status,'registered');const challenge=nativeControl({op:'pair_create'});
 await page.getByLabel('应用内的配对短码').fill(challenge.code);await page.getByLabel('这份 profile 的名字').fill('Synthetic isolated Chromium');await page.getByRole('button',{name:'提交配对请求',exact:true}).click();await page.waitForFunction(()=>document.getElementById('pair-status').textContent.includes('请求已提交') || document.getElementById('error').textContent);
 assert.equal(await page.locator('#error').textContent(),'');const pending=nativeControl({op:'pair_pending'});assert.equal(pending.length,1);assert.equal(pending[0].code,challenge.code);const paired=nativeControl({op:'pair_approve',challenge:challenge.challenge});
 await page.getByRole('button',{name:'刷新状态',exact:true}).click();await page.locator('#pair-status').getByText('已配对 · 桌面连接有效',{exact:true}).waitFor();
 const operationId=crypto.randomUUID();nativeControl({op:'submit',instance_id:paired.instance_id,operation_id:operationId,action:{kind:'webrtc',setting:'disable_non_proxied_udp'}});await page.getByRole('button',{name:'刷新状态',exact:true}).click();await page.getByRole('button',{name:'查看来自桌面的待确认操作',exact:true}).click();await page.getByLabel('我确认以上范围与功能影响').check();await page.getByRole('button',{name:'授予必要权限并执行一次'}).click();await page.locator('#receipts').getByText('webrtc · completed',{exact:true}).waitFor();
 const nativeReceipt=nativeControl({op:'query',instance_id:paired.instance_id,operation_id:operationId});assert.equal(nativeReceipt.phase,'completed');assert.equal(nativeReceipt.receipt.result.effective,'disable_non_proxied_udp');console.log('real native short-code pairing and confirmed operation round trip');
 const screenshot='not-run (functional storage test)';
 const report={screenshot,executable:executablePath||chromium.executablePath(),browser:context.browser()?.version()||'Chromium persistent context',platform:`${os.platform()} ${os.arch()}`,fixture:'localhost target, 127.0.0.1 neighbor; independent temp profile and native home',installation:persistent.installation,startupEvidence,checks:['real popup preview-confirm-execute','Cookie/localStorage/IndexedDB/ServiceWorker/CacheStorage deleted','neighbor stores preserved','target tabs and unrelated host tab with an active target iframe writer closed','outstanding service worker writer stopped by explicit browser restart before separately confirmed deletion','main_frame navigation blocked until explicit release','scoped location block and restore with neighbor permission unchanged','cookie count verified without values in receipt','durable result after full browser/worker restart','new synthetic login preserved on duplicate operation ID','real connectNative short-code request, local approval, browser-confirmed WebRTC, durable host receipt'],receipt:record,nativeReceipt};
 await writeFile(path.join(root,'artifacts/browser-smoke.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({ok:true,checks:report.checks},null,2));
}catch(error){await writeFile(path.join(root,'artifacts/browser-smoke-failure.json'),JSON.stringify({platform:`${os.platform()} ${os.arch()}`,at:new Date().toISOString(),error:error.message,stage:'synthetic native browser flow'},null,2));throw error;}finally{await context?.close();await new Promise(r=>server.close(r));await rm(profile,{recursive:true,force:true});}
