import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../src/engine.js';import {normalizeAction,describe,dataOptions} from '../src/policy.js';
const chromium={browser:'chromium',sites:[{origin:'https://claude.ai',domain:'claude.ai'}]};const firefox={...chromium,browser:'firefox'};
function fake(){const db={},calls=[],rules=[];let setting={value:'default',levelOfControl:'controllable_by_this_extension'};const api={storage:{local:{get:async k=>k===null?structuredClone(db):{[k]:structuredClone(db[k])},set:async v=>Object.assign(db,structuredClone(v)),remove:async k=>{delete db[k];}}},permissions:{contains:async()=>true,getAll:async()=>({permissions:[]})},browsingData:{remove:async(o,t)=>calls.push({o,t,journal:structuredClone(db)}),removeCache:async()=>calls.push('cache')},tabs:{query:async()=>[{id:1,url:'https://claude.ai/a'},{id:2,url:'https://unrelated.example'}],remove:async ids=>calls.push({closed:ids})},webNavigation:{getAllFrames:async()=>[]},declarativeNetRequest:{getDynamicRules:async()=>structuredClone(rules),updateDynamicRules:async({addRules=[],removeRuleIds=[]})=>{for(const id of removeRuleIds){const i=rules.findIndex(r=>r.id===id);if(i>=0)rules.splice(i,1);}rules.push(...structuredClone(addRules));}},cookies:{getAll:async()=>[{value:'SYNTHETIC_SECRET'}]},privacy:{network:{webRTCIPHandlingPolicy:{get:async()=>structuredClone(setting),set:async({value})=>{setting={value,levelOfControl:'controlled_by_this_extension'};},clear:async()=>{setting={value:'default',levelOfControl:'controllable_by_this_extension'};}}}},alarms:{create:async()=>{}}};return {api,db,calls,rules,change:v=>setting=v};}
async function finish(e,p){await e.browserStarted();const next=await e.preview({kind:'finishClear',receiptId:p.id});return e.commit(next.id);}
const clear={kind:'clear',origins:['https://claude.ai'],types:['cookies','localStorage','indexedDB','serviceWorkers','cacheStorage']};
test('preview has cookie expansion; no native API mutation before commit',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);assert.equal(f.calls.length,0);assert.deepEqual(p.preview.effectiveCookieScope,['claude.ai']);assert.equal(p.preview.irreversible,true);await e.commit(p.id);assert.deepEqual(f.calls[0],{closed:[1]});const remove=f.calls.find(c=>c.t);assert.equal(remove.journal[`operation:${p.id}`].phase,'running');assert.deepEqual(remove.t,{serviceWorkers:true});assert(!JSON.stringify(f.db).includes('SYNTHETIC_SECRET'));});
test('durable completed ID cannot clear a newly created login after worker restart',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);await e.commit(p.id);const done=await finish(e,p);const calls=f.calls.length;const restarted=new Engine(f.api,chromium);await restarted.recover();assert.equal((await restarted.commit(done.id)).phase,'completed');assert.equal(f.calls.length,calls);});
test('running journal becomes uncertain, never replays',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);f.db[`operation:${p.id}`].phase='running';const restarted=new Engine(f.api,chromium);await restarted.recover();assert.equal((await restarted.commit(p.id)).phase,'uncertain');assert.equal(f.calls.length,0);});
test('Firefox rejects site HTTP cache and cacheStorage without invoking API',()=>{for(const type of ['cache','cacheStorage'])assert.throws(()=>normalizeAction({...clear,types:[type]},firefox));assert.deepEqual(dataOptions({...clear,types:['cookies'],cookieStoreId:'firefox-container-2'},firefox),{hostnames:['claude.ai'],cookieStoreId:'firefox-container-2'});assert.throws(()=>normalizeAction({...clear,cookieStoreId:'firefox-container-2'},firefox),/Firefox browsingData/);assert.throws(()=>normalizeAction({...clear,types:['serviceWorkers'],cookieStoreId:'firefox-container-2'},firefox),/容器限定/);});
test('app-origin action requires current native pairing',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear,'app');await assert.rejects(e.commit(p.id),/pairing_required/);assert.equal(f.calls.length,0);});
test('same ID bound to immutable action',async()=>{const f=fake(),e=new Engine(f.api,chromium);await e.preview(clear,'local','operation-one');await assert.rejects(e.preview({kind:'clearProfileCache'},'local','operation-one'),/operation_id_conflict/);});
test('restore reveals underlying policy, but respects outside changes',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview({kind:'webrtc',setting:'disable_non_proxied_udp'});await e.commit(p.id);f.change({value:'default_public_interface_only',levelOfControl:'controlled_by_other_extensions'});const restore=await e.preview({kind:'restore',receiptId:p.id});const result=await e.commit(restore.id);assert.equal(result.error.code,'restore_conflict');assert.equal((await f.api.privacy.network.webRTCIPHandlingPolicy.get()).value,'default_public_interface_only');});
test('unapproved sites, irrelevant fields, and missing writer handling rejected',async()=>{assert.throws(()=>normalizeAction({...clear,origins:['https://mail.example']},chromium));assert.throws(()=>normalizeAction({kind:'clearProfileCache',origins:['https://claude.ai']},chromium));const f=fake();await assert.rejects(new Engine(f.api,chromium).preview({...clear,types:['cookies']}),/未选择/);});
test('cleanup isolation persists until explicit release',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);await e.commit(p.id);assert(f.rules.some(r=>r.id===10000));await e.releaseIsolation(p.id);assert.equal(f.rules.length,0);});
test('entire profile cache is a separately named action',()=>{const p=describe(normalizeAction({kind:'clearProfileCache'},firefox),firefox);assert.equal(p.scope,'current-profile');assert.match(p.impact,/整个当前 profile/);});

test('target iframes close their host tab without recording its URL',async()=>{const f=fake();f.api.webNavigation.getAllFrames=async({tabId})=>tabId===2?[{frameId:4,url:'https://claude.ai/embedded'}]:[];const e=new Engine(f.api,chromium),p=await e.preview(clear);assert(p.permissions.permissions.includes('webNavigation'));const r=await e.commit(p.id);assert.deepEqual(f.calls[0],{closed:[1,2]});assert.equal(r.result.embeddedWriterTabCount,1);assert(!JSON.stringify(f.db).includes('unrelated.example'));});
test('released and foreign receipts cannot release another operation isolation',async()=>{const f=fake(),e=new Engine(f.api,chromium),a=await e.preview(clear);await e.commit(a.id);await e.releaseIsolation(a.id);const b=await e.preview(clear);await e.commit(b.id);await e.releaseIsolation(a.id);assert.equal(f.rules.length,1);assert.equal(f.db.cleanupIsolation.operationId,b.id);f.db[`operation:${a.id}`].isolationReleasedAt=undefined;await assert.rejects(e.releaseIsolation(a.id),/不拥有当前隔离/);assert.equal(f.rules.length,1);});
test('failed removal retains owned isolation and never repeats deletion',async()=>{const f=fake();f.api.browsingData.remove=async()=>{throw new Error('synthetic interruption');};const e=new Engine(f.api,chromium),p=await e.preview(clear);assert.equal((await e.commit(p.id)).phase,'uncertain');assert.equal(f.db.cleanupIsolation.operationId,p.id);assert.equal(f.rules.length,1);await e.releaseIsolation(p.id);assert.equal(f.rules.length,0);});
test('Firefox container closes only its frame hosts and validates store before mutations',async()=>{const f=fake();f.api.cookies.getAllCookieStores=async()=>[{id:'firefox-container-2'}];f.api.tabs.query=async()=>[{id:1,url:'https://claude.ai/a',cookieStoreId:'firefox-container-2'},{id:2,url:'https://claude.ai/a',cookieStoreId:'firefox-container-3'}];const e=new Engine(f.api,firefox);const a={...clear,types:['cookies','localStorage','indexedDB'],cookieStoreId:'firefox-container-2'};const p=await e.preview(a);assert(p.permissions.permissions.includes('cookies'));await e.commit(p.id);const r=await finish(e,p);assert.equal(r.phase,'completed');assert.deepEqual(f.calls[0],{closed:[1]});assert.deepEqual(f.calls.find(c=>c.t).o,{hostnames:['claude.ai'],cookieStoreId:'firefox-container-2'});assert.equal(r.result.writerHandling,'container-frames-closed-service-workers-not-verified');await e.releaseIsolation(r.id);const invalid=await e.preview({...a,cookieStoreId:'firefox-container-9'});const count=f.calls.length;assert.equal((await e.commit(invalid.id)).error.code,'unknown_cookie_store');assert.equal(f.calls.length,count);assert.equal(f.rules.length,0);});
test('successful WebRTC restore reads back underlying control instead of asserting a stale value',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview({kind:'webrtc',setting:'disable_non_proxied_udp'});await e.commit(p.id);const r=await e.preview({kind:'restore',receiptId:p.id});const restored=await e.commit(r.id);assert.equal(restored.phase,'completed');assert.equal(restored.result.verification,'effective-readback');assert.equal(restored.result.effective.levelOfControl,'controllable_by_this_extension');});

test('cleanup requires a real browser startup event and consumes preparation once',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);const prepared=await e.commit(p.id);assert.equal(prepared.phase,'awaiting-browser-restart');assert.equal(f.calls.filter(c=>c.t).length,1);await assert.rejects(e.preview({kind:'finishClear',receiptId:p.id}),/请完整退出/);await new Engine(f.api,chromium).recover();await assert.rejects(e.preview({kind:'finishClear',receiptId:p.id}),/请完整退出/);const done=await finish(e,p);assert.equal(done.phase,'completed');assert.equal(f.db.cleanupIsolation.operationId,done.id);await assert.rejects(e.preview({kind:'finishClear',receiptId:p.id}),/cleanup_preparation_not_active/);assert.equal((await e.commit(done.id)).phase,'completed');});
test('DNR readback key order does not prevent continuing the same isolation',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);await e.commit(p.id);f.api.declarativeNetRequest.getDynamicRules=async()=>f.rules.map(r=>({condition:r.condition,action:r.action,priority:r.priority,id:r.id}));const done=await finish(e,p);assert.equal(done.phase,'completed');});
