import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../src/engine.js';import {normalizeAction,describe,dataOptions} from '../src/policy.js';
const chromium={browser:'chromium',sites:[{origin:'https://claude.ai',domain:'claude.ai'}]};const firefox={...chromium,browser:'firefox'};
function fake(){const db={},calls=[],rules=[];let setting={value:'default',levelOfControl:'controllable_by_this_extension'};const api={storage:{local:{get:async k=>k===null?structuredClone(db):{[k]:structuredClone(db[k])},set:async v=>Object.assign(db,structuredClone(v)),remove:async k=>{delete db[k];}}},permissions:{contains:async()=>true,getAll:async()=>({permissions:[]})},browsingData:{remove:async(o,t)=>calls.push({o,t,journal:structuredClone(db)}),removeCache:async()=>calls.push('cache')},tabs:{query:async()=>[{id:1,url:'https://claude.ai/a'},{id:2,url:'https://unrelated.example'}],remove:async ids=>calls.push({closed:ids})},declarativeNetRequest:{getDynamicRules:async()=>structuredClone(rules),updateDynamicRules:async({addRules=[],removeRuleIds=[]})=>{for(const id of removeRuleIds){const i=rules.findIndex(r=>r.id===id);if(i>=0)rules.splice(i,1);}rules.push(...structuredClone(addRules));}},cookies:{getAll:async()=>[{value:'SYNTHETIC_SECRET'}]},privacy:{network:{webRTCIPHandlingPolicy:{get:async()=>structuredClone(setting),set:async({value})=>{setting={value,levelOfControl:'controlled_by_this_extension'};},clear:async()=>{setting={value:'default',levelOfControl:'controllable_by_this_extension'};}}}},alarms:{create:async()=>{}}};return {api,db,calls,rules,change:v=>setting=v};}
const clear={kind:'clear',origins:['https://claude.ai'],types:['cookies','localStorage','indexedDB','serviceWorkers','cacheStorage']};
test('preview has cookie expansion; no native API mutation before commit',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);assert.equal(f.calls.length,0);assert.deepEqual(p.preview.effectiveCookieScope,['claude.ai']);assert.equal(p.preview.irreversible,true);await e.commit(p.id);assert.deepEqual(f.calls[0],{closed:[1]});const remove=f.calls.find(c=>c.t);assert.equal(remove.journal[`operation:${p.id}`].phase,'running');assert.deepEqual(remove.t,{serviceWorkers:true});assert(!JSON.stringify(f.db).includes('SYNTHETIC_SECRET'));});
test('durable completed ID cannot clear a newly created login after worker restart',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);await e.commit(p.id);const calls=f.calls.length;const restarted=new Engine(f.api,chromium);await restarted.recover();assert.equal((await restarted.commit(p.id)).phase,'completed');assert.equal(f.calls.length,calls);});
test('running journal becomes uncertain, never replays',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);f.db[`operation:${p.id}`].phase='running';const restarted=new Engine(f.api,chromium);await restarted.recover();assert.equal((await restarted.commit(p.id)).phase,'uncertain');assert.equal(f.calls.length,0);});
test('Firefox rejects site HTTP cache and cacheStorage without invoking API',()=>{for(const type of ['cache','cacheStorage'])assert.throws(()=>normalizeAction({...clear,types:[type]},firefox));assert.deepEqual(dataOptions({...clear,types:['cookies'],cookieStoreId:'firefox-container-2'},firefox),{hostnames:['claude.ai'],cookieStoreId:'firefox-container-2'});assert.throws(()=>normalizeAction({...clear,cookieStoreId:'firefox-container-2'},firefox),/Firefox browsingData/);assert.throws(()=>normalizeAction({...clear,types:['serviceWorkers'],cookieStoreId:'firefox-container-2'},firefox),/容器限定/);});
test('app-origin action requires current native pairing',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear,'app');await assert.rejects(e.commit(p.id),/pairing_required/);assert.equal(f.calls.length,0);});
test('same ID bound to immutable action',async()=>{const f=fake(),e=new Engine(f.api,chromium);await e.preview(clear,'local','operation-one');await assert.rejects(e.preview({kind:'clearProfileCache'},'local','operation-one'),/operation_id_conflict/);});
test('restore reveals underlying policy, but respects outside changes',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview({kind:'webrtc',setting:'disable_non_proxied_udp'});await e.commit(p.id);f.change({value:'default_public_interface_only',levelOfControl:'controlled_by_other_extensions'});const restore=await e.preview({kind:'restore',receiptId:p.id});const result=await e.commit(restore.id);assert.equal(result.error.code,'restore_conflict');assert.equal((await f.api.privacy.network.webRTCIPHandlingPolicy.get()).value,'default_public_interface_only');});
test('unapproved sites, irrelevant fields, and missing writer handling rejected',async()=>{assert.throws(()=>normalizeAction({...clear,origins:['https://mail.example']},chromium));assert.throws(()=>normalizeAction({kind:'clearProfileCache',origins:['https://claude.ai']},chromium));const f=fake();await assert.rejects(new Engine(f.api,chromium).preview({...clear,types:['cookies']}),/未选择/);});
test('cleanup isolation persists until explicit release',async()=>{const f=fake(),e=new Engine(f.api,chromium),p=await e.preview(clear);await e.commit(p.id);assert(f.rules.some(r=>r.id===10000));await e.releaseIsolation(p.id);assert.equal(f.rules.length,0);});
test('entire profile cache is a separately named action',()=>{const p=describe(normalizeAction({kind:'clearProfileCache'},firefox),firefox);assert.equal(p.scope,'current-profile');assert.match(p.impact,/整个当前 profile/);});
